FROM ubuntu:latest
MAINTAINER hollands

RUN apt-get -y update
RUN apt-get install -y build-essential
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y default-jre

CMD mkdir ~/Mallochite
COPY . ~/Mallochite

